<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\css\**" />
    <Compile Remove="wwwroot\images\**" />
    <Compile Remove="wwwroot\img\**" />
    <Compile Remove="wwwroot\js\**" />
    <Compile Remove="wwwroot\Karma Shop-doc\**" />
    <Compile Remove="wwwroot\lib\**" />
    <Compile Remove="wwwroot\scss\**" />
    <Content Remove="wwwroot\css\**" />
    <Content Remove="wwwroot\images\**" />
    <Content Remove="wwwroot\img\**" />
    <Content Remove="wwwroot\js\**" />
    <Content Remove="wwwroot\Karma Shop-doc\**" />
    <Content Remove="wwwroot\lib\**" />
    <Content Remove="wwwroot\scss\**" />
    <EmbeddedResource Remove="wwwroot\css\**" />
    <EmbeddedResource Remove="wwwroot\images\**" />
    <EmbeddedResource Remove="wwwroot\img\**" />
    <EmbeddedResource Remove="wwwroot\js\**" />
    <EmbeddedResource Remove="wwwroot\Karma Shop-doc\**" />
    <EmbeddedResource Remove="wwwroot\lib\**" />
    <EmbeddedResource Remove="wwwroot\scss\**" />
    <None Remove="wwwroot\css\**" />
    <None Remove="wwwroot\images\**" />
    <None Remove="wwwroot\img\**" />
    <None Remove="wwwroot\js\**" />
    <None Remove="wwwroot\Karma Shop-doc\**" />
    <None Remove="wwwroot\lib\**" />
    <None Remove="wwwroot\scss\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.26" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.26">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.23" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Controllers\" />
    <Folder Include="Data\" />
    <Folder Include="Models\" />
    <Folder Include="Views\Shared\" />
  </ItemGroup>

</Project>
